
package kz.idsoftware.gcvp.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BillingServiceImplService", targetNamespace = "http://ws.gcvp.idsoftware.kz/", wsdlLocation = "file:/D:/_GCVP/billing-test_bak/src/main/java/BillingWS.xml")
public class BillingServiceImplService
    extends Service
{

    private final static URL BILLINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(kz.idsoftware.gcvp.ws.BillingServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = kz.idsoftware.gcvp.ws.BillingServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/_GCVP/billing-test_bak/src/main/java/BillingWS.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/_GCVP/billing-test_bak/src/main/java/BillingWS.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILLINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public BillingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingServiceImplService() {
        super(BILLINGSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.gcvp.idsoftware.kz/", "BillingServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns BillingService
     */
    @WebEndpoint(name = "BillingServiceImplPort")
    public BillingService getBillingServiceImplPort() {
        return super.getPort(new QName("http://ws.gcvp.idsoftware.kz/", "BillingServiceImplPort"), BillingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingService
     */
    @WebEndpoint(name = "BillingServiceImplPort")
    public BillingService getBillingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gcvp.idsoftware.kz/", "BillingServiceImplPort"), BillingService.class, features);
    }

}
