#!/bin/sh

mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_ADM_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_SOAP_AML_OUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_BGW_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_BILLING_SBOLRS_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_BSS_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_INPUT_CAKD >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_CRM_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_CRM_RETAIL_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_CRM_RETAIL_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_CRM_RETAIL_OUTPUT_WAY >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_DBO_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_EPK_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_IPT_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_KOLIBRI_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_MB_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_TRANSACTRMB_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_PRAGMA >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_PRAGMA_NEW_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_PRAGMA_NEW_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_PRAGMA_NEW_TSM >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_WAY_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_SBOLRS_WAY_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_SBOLRS_BILLING_INPUT >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_BILLING_STAT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_RSROUTER_WAY_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_QPRSROUTER >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_RSROUTER_WAYFIN_INPUT >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_RSROUTER_QPRAGMA_INPUT >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_SAP_OUTPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_SAP_INPUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_HTTP_SBOL >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_HTTP_SBOLRS >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o WAY_SBOLRS >> "./delete_configure.log" 
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_TALLIMAN_OUT >> "./delete_configure.log"
mqsideleteconfigurableservice MKZ.ESB.ADP1_BRK -c Aggregation -o A_TRANSACT_OUTPUT >> "./delete_configure.log" 

echo "**** END ****"
