
package kz.gcvp.billing.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BillingWSImplService", targetNamespace = "http://impl.ws.billing.gcvp.kz/", wsdlLocation = "https://gcvp.idsoftware.kz/billing-ws/ws/BillingWS?wsdl")
public class BillingWSImplService
    extends Service
{

    private final static URL BILLINGWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLINGWSIMPLSERVICE_EXCEPTION;
    private final static QName BILLINGWSIMPLSERVICE_QNAME = new QName("http://impl.ws.billing.gcvp.kz/", "BillingWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://gcvp.idsoftware.kz/billing-ws/ws/BillingWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLINGWSIMPLSERVICE_WSDL_LOCATION = url;
        BILLINGWSIMPLSERVICE_EXCEPTION = e;
    }

    public BillingWSImplService() {
        super(__getWsdlLocation(), BILLINGWSIMPLSERVICE_QNAME);
    }

    public BillingWSImplService(WebServiceFeature... features) {
        //super(__getWsdlLocation(), BILLINGWSIMPLSERVICE_QNAME, features);
    	super(__getWsdlLocation(), BILLINGWSIMPLSERVICE_QNAME);
    }

    public BillingWSImplService(URL wsdlLocation) {
        super(wsdlLocation, BILLINGWSIMPLSERVICE_QNAME);
    }

    public BillingWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        //super(wsdlLocation, BILLINGWSIMPLSERVICE_QNAME, features);
        super(wsdlLocation, BILLINGWSIMPLSERVICE_QNAME);
    }

    public BillingWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        //super(wsdlLocation, serviceName, features);
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns BillingWS
     */
    @WebEndpoint(name = "BillingWSImplPort")
    public BillingWS getBillingWSImplPort() {
        return super.getPort(new QName("http://impl.ws.billing.gcvp.kz/", "BillingWSImplPort"), BillingWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingWS
     */
    @WebEndpoint(name = "BillingWSImplPort")
    public BillingWS getBillingWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.billing.gcvp.kz/", "BillingWSImplPort"), BillingWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLINGWSIMPLSERVICE_EXCEPTION!= null) {
            throw BILLINGWSIMPLSERVICE_EXCEPTION;
        }
        return BILLINGWSIMPLSERVICE_WSDL_LOCATION;
    }

}
