
package kz.gcvp.billing.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import kz.gcvp.billing.ws.DeductionDetailedResponse;
import kz.gcvp.billing.ws.DeductionRequest;
import kz.gcvp.billing.ws.DeductionShortResponse;
import kz.gcvp.billing.ws.ObjectFactory;
import kz.gcvp.billing.ws.PensionRequest;
import kz.gcvp.billing.ws.PensionResponse;
import kz.gcvp.billing.ws.SocialRequest;
import kz.gcvp.billing.ws.SocialResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillingWS", targetNamespace = "http://ws.billing.gcvp.kz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillingWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns kz.gcvp.billing.ws.DeductionShortResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeductionShortInfo", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetDeductionShortInfo")
    @ResponseWrapper(localName = "getDeductionShortInfoResponse", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetDeductionShortInfoResponse")
    public DeductionShortResponse getDeductionShortInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        DeductionRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns kz.gcvp.billing.ws.DeductionDetailedResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeductionDetailedInfo", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetDeductionDetailedInfo")
    @ResponseWrapper(localName = "getDeductionDetailedInfoResponse", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetDeductionDetailedInfoResponse")
    public DeductionDetailedResponse getDeductionDetailedInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        DeductionRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns kz.gcvp.billing.ws.PensionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPensionInfo", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetPensionInfo")
    @ResponseWrapper(localName = "getPensionInfoResponse", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetPensionInfoResponse")
    public PensionResponse getPensionInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        PensionRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns kz.gcvp.billing.ws.SocialResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSocialInfo", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetSocialInfo")
    @ResponseWrapper(localName = "getSocialInfoResponse", targetNamespace = "http://ws.billing.gcvp.kz/", className = "kz.gcvp.billing.ws.GetSocialInfoResponse")
    public SocialResponse getSocialInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        SocialRequest arg0);

}
